### ISSUE TITLE
Menu items are not displayer on Windows/Linux

### ISSUE THREAD

**Issue by TheBronx** [chabou/hyper-broadcast#1]
Just installed the plugin, but it is not working.
There is no entry menu, the config is missing, no red indicators...
I have added the config manually, but still nothing. 

When I change the config, I can see this in the developer console:
`|HYPER-BROADCAST| reload renderer config`

But thats all, the plugin is completely invisible and the commands do not work.

**Comment by chabou** [comment]
Can you give me your config file and more information about your OS ?

**Comment by TheBronx** [comment]
Ubuntu 16.04, Hyper.js with plugin hyperlayout (https://www.npmjs.com/package/hyperlayout).
The config is just the default one, I've just added the broadcast config as the README says:

	broadcast: {
	  debug: false,
	  hotkeys: {
		selectCurrentPane: 'Command+Alt+Shift+B',
		selectCurrentTabPanes: 'Command+Alt+B',
		selectAllPanes: 'Command+Shift+B',
		toggleCurrentPane: 'Command+Alt+Control+Shift+B'
	  },
	  indicatorStyle: {
		position: 'absolute',
		top: 5,
		right: 10,
		borderRadius: '50%',
		width: '10px',
		height: '10px',
		background: 'red'
	  }
	}

Then I've tried replacing "Command" with "CommandOrControl" and a few more things, but without results.

**Comment by jonathandelgado** [comment]
Did some investigating on this. Looks like the keybinds/menu is being added to the `Shell` menu [here](https://github.com/chabou/hyper-broadcast/blob/master/index.js#L67).

Not sure if `Shell` exists on OSX, but for Windows/Linux, it doesn't. Switching it to `Plugins` fixed this for me.

**Comment by chabou** [comment]
@jonathandelgado Thank you so much for your investigation! Now ([v0.9.1](https://github.com/chabou/hyper-broadcast/releases/tag/v0.9.1)), menu items are well displayed. 

But default shortcuts are so wrong in Windows (and maybe Linux). I need to change this, but the way that `Hyper` handle plugins hotkeys is going to change very soon. I'll wait for these changes to be done.
